### ISSUE TITLE
Support for circular structures

### ISSUE THREAD

**Issue by pcafstockf** [s3u/JSONPath#112]
While JSON doesn't support circular structures, this project's description "... selectively extract data from JSON documents (and JavaScript objects)." does include "JavaScript objects".  :-)

In my case, a hacked replacement of JSONPath.prototype._walk served my needs (searching an AST) and allowed me to use this great library.  
However, more flexible/official support would be nice.

**Comment by errodrigues** [comment]
I'm facing this issue as well, and getting
```
[ ERROR ] UnexpectedAuditFailure: Maximum call stack size exceeded - RangeError: Maximum call stack size exceeded
        at /test/js/core/node_modules/jsonpath-plus/dist/index-node-cjs.cjs:586:7
        at Array.forEach (<anonymous>)
        at JSONPath.Object.<anonymous>.JSONPath._walk (/test/js/core/target/node_modules/jsonpath-plus/dist/index-node-cjs.cjs:585:22)
        at JSONPath.Object.<anonymous>.JSONPath._trace (/test/js/core/target/node_modules/jsonpath-plus/dist/index-node-cjs.cjs:429:10)
       (...)
```
