### ISSUE TITLE
Cannot find module jsonpath/lib/aesprim.js

### ISSUE THREAD

**Issue by liquid** [s3u/JSONPath#74]
I'm trying to install Ghost on FreeBSD and it seems like it depends on the JSONPath package that fails to install:

```
# npm install --production
npm WARN cannot run in wd ghost@0.7.8 npm install semver && node -e "require('./core/server/utils/startup-check.js').nodeVersion()" (wd=/usr/home/ghost/ghost)
/
> jsonpath@0.2.2 postinstall /usr/home/ghost/ghost/node_modules/jsonpath
> node lib/aesprim.js > generated/aesprim-browser.js


module.js:340
    throw err;
          ^
Error: Cannot find module '/usr/home/ghost/ghost/node_modules/jsonpath/lib/aesprim.js'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:935:3
npm ERR! FreeBSD 10.3-RELEASE
npm ERR! argv "node" "/usr/local/bin/npm" "install" "--production"
npm ERR! node v0.10.40
npm ERR! npm  v2.14.7
npm ERR! code ELIFECYCLE

npm ERR! jsonpath@0.2.2 postinstall: `node lib/aesprim.js > generated/aesprim-browser.js`
npm ERR! Exit status 8
npm ERR! 
npm ERR! Failed at the jsonpath@0.2.2 postinstall script 'node lib/aesprim.js > generated/aesprim-browser.js'.
npm ERR! This is most likely a problem with the jsonpath package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node lib/aesprim.js > generated/aesprim-browser.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls jsonpath
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /usr/home/ghost/ghost/npm-debug.log
```

The relevant lines (as I thought) from `nom-debug.log` as follows:

```
2023 info install jsonpath@0.2.2
2024 info postinstall jsonpath@0.2.2
2025 verbose unsafe-perm in lifecycle false
2026 info jsonpath@0.2.2 Failed to exec postinstall script
2027 verbose unlock done using /root/.npm/_locks/jsonpath-b4d7f2175e23260d.lock for /usr/home/ghost/ghost/node_modules/jsonpath
2028 verbose stack Error: jsonpath@0.2.2 postinstall: `node lib/aesprim.js > generated/aesprim-browser.js`
2028 verbose stack Exit status 8
2028 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:214:16)
2028 verbose stack     at EventEmitter.emit (events.js:98:17)
2028 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:24:14)
2028 verbose stack     at ChildProcess.emit (events.js:98:17)
2028 verbose stack     at maybeClose (child_process.js:766:16)
2028 verbose stack     at Process.ChildProcess._handle.onexit (child_process.js:833:5)
2029 verbose pkgid jsonpath@0.2.2
2030 verbose cwd /usr/home/ghost/ghost
2031 error FreeBSD 10.3-RELEASE
2032 error argv "node" "/usr/local/bin/npm" "install" "--production"
2033 error node v0.10.40
2034 error npm  v2.14.7
2035 error code ELIFECYCLE
2036 error jsonpath@0.2.2 postinstall: `node lib/aesprim.js > generated/aesprim-browser.js`
2036 error Exit status 8
2037 error Failed at the jsonpath@0.2.2 postinstall script 'node lib/aesprim.js > generated/aesprim-browser.js'.
2037 error This is most likely a problem with the jsonpath package,
2037 error not with npm itself.
2037 error Tell the author that this fails on your system:
2037 error     node lib/aesprim.js > generated/aesprim-browser.js
2037 error You can get their info via:
2037 error     npm owner ls jsonpath
2037 error There is likely additional logging output above.
2038 verbose exit [ 1, true ]
2039 verbose unbuild node_modules/jsonpath
2040 info preuninstall jsonpath@0.2.2
2041 info uninstall jsonpath@0.2.2
2042 verbose unbuild rmStuff jsonpath@0.2.2 from /usr/home/ghost/ghost/node_modules
2043 info postuninstall jsonpath@0.2.2
2044 silly gentlyRm /usr/home/ghost/ghost/node_modules/jsonpath is being purged from base /usr/home/ghost/ghost
2045 verbose gentlyRm don't care about contents; nuking /usr/home/ghost/ghost/node_modules/jsonpath
2046 silly vacuum-fs purging /usr/home/ghost/ghost/node_modules/jsonpath
2047 silly vacuum-fs quitting because other entries in /usr/home/ghost/ghost/node_modules
```

I'm not sure what needs to be done but am more than happy to help debugging. Any help would be appreciated.

**Comment by brettz9** [comment]
`jsonpath` is not our package. It is listed at https://www.npmjs.com/package/jsonpath which points to https://github.com/dchester/jsonpath

We did use https://www.npmjs.com/package/JSONPath (the paths were originally case insensitive), but because issues surfaced as far as case insensitivity, we moved to "jsonpath-plus" (which also fit because we have added more operators to the originally spec'd syntax).

I'll close, but feel free to comment further.
